core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala, core/src/main/scala/org/apache/spark/executor/CoarseGrainedExecutorBackend.scala, core/src/main/scala/org/apache/spark/scheduler/KerberosUser.scala, core/src/main/scala/org/apache/spark/scheduler/KerberosUtil.scala, core/src/main/scala/org/apache/spark/scheduler/ResultTask.scala, core/src/main/scala/org/apache/spark/scheduler/ShuffleMapTask.scala, core/src/main/scala/org/apache/spark/security/HDFSConfig.scala, core/src/main/scala/org/apache/spark/security/KerberosConfig.scala, core/src/main/scala/org/apache/spark/security/SSLConfig.scala, core/src/main/scala/org/apache/spark/security/VaultHelper.scala, mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala, mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosSchedulerBackendUtil.scala
add calico support to Spark 2.1.0
Manual testing in EOS Cluster with Bird installed in all the Mesos masters.
=> calico integration

core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala, core/src/main/scala/org/apache/spark/security/ConfigSecurity.scala
bug fixing detected by Stratio
Doesn't have been tested
=> Sparta bug fixing

core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala, core/src/main/scala/org/apache/spark/security/ConfigSecurity.scala
HDFS Config bug fixed
This PR haven't been tested
=> fixed Only HDFS configuration bug

Jenkinsfile
change the docker image name to Stratio-spark-R1 in order to improve tractability
This changes hadn't been tested.
=> new docker image

DockerfileDispatcher, DockerfileHistory, Jenkinsfile, docker/dispatcher/init.sh, docker/dispatcher/service, docker/historyServer/commons.sh, docker/historyServer/entrypoint.sh, docker/historyServer/kms_utils.sh, mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala, mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala, mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosFineGrainedSchedulerBackend.scala, mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosSchedulerBackendUtil.scala
calico needs two networks one for the Driver and another for the Executrors so we need to change this configuration:
`spark.mesos.docker.mesos.network.name`
for:
````
spark.mesos.driver.docker.mesos.network.name
spark.mesos.executor.docker.mesos.network.name
````
Besides we need two images one for the Spark HistoryServer and another for the Stratio Spark Dispatcher.
These patch hasn't been tested.
=> Branch stratio spark development

DockerfileDispatcher, core/src/main/scala/org/apache/spark/security/VaultHelper.scala, docker/dispatcher/service, docker/dispatcher/spark-env.sh, mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala, mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
Change Vault temp tokens for authentication for Vault's appRole authentication.
THIS PR HAD TO BE MERGER AFETER #11 
tested in a DC/OS 1.8.8 cluster with calico.
=> Dynamic authentication

Jenkinsfile, core/src/main/scala/org/apache/spark/SecurityManager.scala, core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala, core/src/main/scala/org/apache/spark/executor/CoarseGrainedExecutorBackend.scala, core/src/main/scala/org/apache/spark/security/ConfigSecurity.scala, core/src/main/scala/org/apache/spark/security/SSLConfig.scala, core/src/main/scala/org/apache/spark/security/VaultHelper.scala, docker/dispatcher/spark-env.sh, pom.xml
In this pull request we are gonna try to connect to different datastores using a generic way to connecting them via TLS
Launching a Spark Job with JDBC connection to a Postgres with TLS.
=> TLS Integration

CHANGELOG.md, docker/historyServer/entrypoint.sh
history server env vars fixed.
Launched Spark applicactions with event log dir enable in an EOS 1.8 cluster.
=> bug fixing

DockerfileDispatcher, Jenkinsfile, resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
Reverted to download kms-utils
=> reverted kms download

DockerfileHistory, Jenkinsfile
(Please fill in changes proposed in this fix)
fix History Server entrypoint permision bug
This PR hadn't been tested yet
=> fix History Server entrypoint permision bug

Jenkinsfile, core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala, core/src/main/scala/org/apache/spark/security/ConfigSecurity.scala, resource-managers/mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala, resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
=> revert change hosts

Jenkinsfile, core/src/main/scala/org/apache/spark/security/HDFSConfig.scala
add timeout to a HDFSConfig get.
This patch has not been tested yet.
=> add HDFSTimeout

core/src/main/scala/org/apache/spark/security/HDFSConfig.scala
add timeout to a HDFSConfig get.
This patch has not been tested yet.
=> add timeout for HDFS config files download

Jenkinsfile, core/src/main/scala/org/apache/spark/security/ConfigSecurity.scala, core/src/main/scala/org/apache/spark/security/DBConfig.scala, core/src/main/scala/org/apache/spark/security/VaultHelper.scala
add User Pass extraction from Vault
This PR hadn't been tested yet.
=> add User Pass extraction from Vault

CHANGELOG.md, core/src/main/scala/org/apache/spark/deploy/history/HistoryServer.scala, core/src/main/scala/org/apache/spark/security/ConfigSecurity.scala
History will be able to read the events log from a HDFS with High Ability
This PR Hasn't been tested
=> History Server able to read from HDFS in HA

Jenkinsfile, core/src/main/scala/org/apache/spark/broadcast/TorrentSecretBroadcast.scala
Secret Broadcast now obtain secrets dynamically
In a Stratio DC 0.17.1
=> added dynamic solution for Secret Broadcast

CHANGELOG.md, core/src/main/scala/org/apache/spark/security/ConfigSecurity.scala, core/src/main/scala/org/apache/spark/security/MesosConfig.scala, core/src/main/scala/org/apache/spark/security/VaultHelper.scala, resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosSchedulerUtils.scala
Mesos principal and mesos secret are configurable via environment variable
Manually in a Stratio DCS environment
=> mesos security configurable

Jenkinsfile
(Please fill in changes proposed in this fix)
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)
=> [AT] Update DCOS CLI for removed token expiration

DockerfileDriver, Jenkinsfile, core/src/main/scala/org/apache/spark/SparkContext.scala, docker/driver/driver.sh, docker/driver/spark-env.sh, resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala, streaming/src/main/scala/org/apache/spark/streaming/scheduler/StreamingListenerBus.scala
This PR hadn't been tested yet
=> [SPK-237] Remove streaming tab and  [SPK-236] Fix applications incomplete

Jenkinsfile
(Please fill in changes proposed in this fix)
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)
=> parameterize groups to be run in Jenkinsfile
